name: Check Logs

on:
  workflow_dispatch:
    inputs:
      instance-ip:
        description: 'Instance IP address'
        required: true
      environment:
        description: 'Environment (dev or staging)'
        required: true

jobs:
  check-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Check logs in AWS
        run: |
          if [ "${{ github.event.inputs.environment }}" = "dev" ]; then
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          elif [ "${{ github.event.inputs.environment }}" = "staging" ]; then
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          else
            echo "Invalid environment specified."
            exit 1
          fi

          aws configure set region ${{ github.event.inputs.region }}

          # Check service status and fetch logs
          INSTANCE_IP="${{ github.event.inputs.instance-ip }}"
          LOGS=$(ssh ec2-user@${INSTANCE_IP} "cat /home/builds/cb_app_server/tomcat_logs/catalina.out")

          # Display logs in GitHub Actions UI
          echo "Logs: $LOGS"
